[package]
name = "home_site"
version = "0.1.0"
authors = ["luuk <luuk.wester@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
sysfs_gpio = "*"
rocket-simpleauth = "0.4.0"
dotenv = "0.11.0"
jsonwebtoken = "2"
argon2rs = "*"
rand = "*"
serde = "*"
serde_derive = "*"

[dependencies.diesel]
version = "*"
default-features = false
features = ["postgres", ]

[dependencies.rocket_contrib]
version = "*"
default-features = false
features = ["handlebars_templates", ]
